import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{js,jsx,ts,tsx}',
    ],

    darkMode: 'class',

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'on-surface':                '#131b2e',
                'inverse-on-surface':        '#eef0ff',
                'tertiary-fixed-dim':        '#ffb596',
                'tertiary-container':        '#bc4800',
                'error-container':           '#ffdad6',
                'on-secondary':              '#ffffff',
                'on-error':                  '#ffffff',
                'error':                     '#ba1a1a',
                'primary-fixed':             '#dbe1ff',
                'on-secondary-fixed':        '#0b1c30',
                'on-error-container':        '#93000a',
                'surface-container':         '#eaedff',
                'on-tertiary':               '#ffffff',
                'inverse-surface':           '#283044',
                'on-secondary-fixed-variant':'#38485d',
                'surface-container-high':    '#e2e7ff',
                'secondary':                 '#505f76',
                'surface-dim':               '#d2d9f4',
                'surface-tint':              '#0053db',
                'surface-container-low':     '#f2f3ff',
                'inverse-primary':           '#b4c5ff',
                'on-primary-container':      '#eeefff',
                'on-primary':                '#ffffff',
                'secondary-container':       '#d0e1fb',
                'secondary-fixed':           '#d3e4fe',
                'on-tertiary-container':     '#ffede6',
                'tertiary':                  '#943700',
                'surface-variant':           '#dae2fd',
                'on-tertiary-fixed':         '#360f00',
                'on-primary-fixed-variant':  '#003ea8',
                'secondary-fixed-dim':       '#b7c8e1',
                'surface-bright':            '#faf8ff',
                'primary':                   '#004ac6',
                'primary-container':         '#2563eb',
                'outline':                   '#737686',
                'on-secondary-container':    '#54647a',
                'surface-container-highest': '#dae2fd',
                'on-primary-fixed':          '#00174b',
                'background':                '#faf8ff',
                'surface':                   '#faf8ff',
                'on-tertiary-fixed-variant': '#7d2d00',
                'surface-container-lowest':  '#ffffff',
                'outline-variant':           '#c3c6d7',
                'tertiary-fixed':            '#ffdbcd',
                'on-surface-variant':        '#434655',
                'primary-fixed-dim':         '#b4c5ff',
                'on-background':             '#131b2e',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                sm: '0.5rem',
                xs: '0.25rem',
                md: '1rem',
                lg: '1.5rem',
                gutter: '1rem',
                unit: '4px',
                xl: '2rem',
                'container-max': '1440px',
            },
            fontSize: {
                'body-lg':    ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-sm':   ['11px', { lineHeight: '14px', fontWeight: '500' }],
                'body-sm':    ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'headline-lg':['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'display':    ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md':    ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-md':   ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-md':['20px', { lineHeight: '28px', fontWeight: '600' }],
            },
        },
    },

    plugins: [forms],
};
